language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r marketing *
  - mkdir -p deploy
  - mv marketing.zip deploy/marketing.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ec2-dev-ubuntu-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ec2-dev-ubuntu-build
    key: marketing.zip
    bundle_type: zip
    application: ec2-linux
    deployment_group: ec2-linux-group
    region: ap-northeast-2
    wait-until-deployed: true


notifications:
  email:
    recipients:
      - jinhoon0319@gmail.com