language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./gradlew

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - jinhoon0319@gmail.com