spring:
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name:
  jpa:
    database-platform:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

logging.level:
  org.hibernate.SQL: debug
